name: build games
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - voice/**
jobs:
  push:
    name: "yolks:voice_${{ matrix.game }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        voice:
          - teaspeak
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./voice/${{ matrix.game }}
          file: ./voice/${{ matrix.game }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
             ghcr.io/pteroforge/voice:${{ matrix.game }}
